/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedVinRouteImport } from './routes/_authed/vin'
import { Route as AuthedStockRouteImport } from './routes/_authed/stock'
import { Route as AuthedSauvegardeRouteImport } from './routes/_authed/sauvegarde'
import { Route as AuthedRechercheRouteImport } from './routes/_authed/recherche'
import { Route as AuthedImpressionRouteImport } from './routes/_authed/impression'
import { Route as AuthedImportRouteImport } from './routes/_authed/import'
import { Route as AuthedEtiquettesRouteImport } from './routes/_authed/etiquettes'
import { Route as AuthedEntreeRouteImport } from './routes/_authed/entree'
import { Route as AuthedCorbeilleRouteImport } from './routes/_authed/corbeille'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVinRoute = AuthedVinRouteImport.update({
  id: '/vin',
  path: '/vin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockRoute = AuthedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSauvegardeRoute = AuthedSauvegardeRouteImport.update({
  id: '/sauvegarde',
  path: '/sauvegarde',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRechercheRoute = AuthedRechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedImpressionRoute = AuthedImpressionRouteImport.update({
  id: '/impression',
  path: '/impression',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedImportRoute = AuthedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEtiquettesRoute = AuthedEtiquettesRouteImport.update({
  id: '/etiquettes',
  path: '/etiquettes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEntreeRoute = AuthedEntreeRouteImport.update({
  id: '/entree',
  path: '/entree',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCorbeilleRoute = AuthedCorbeilleRouteImport.update({
  id: '/corbeille',
  path: '/corbeille',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/auth': typeof AuthRoute
  '/corbeille': typeof AuthedCorbeilleRoute
  '/entree': typeof AuthedEntreeRoute
  '/etiquettes': typeof AuthedEtiquettesRoute
  '/import': typeof AuthedImportRoute
  '/impression': typeof AuthedImpressionRoute
  '/recherche': typeof AuthedRechercheRoute
  '/sauvegarde': typeof AuthedSauvegardeRoute
  '/stock': typeof AuthedStockRoute
  '/vin': typeof AuthedVinRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/corbeille': typeof AuthedCorbeilleRoute
  '/entree': typeof AuthedEntreeRoute
  '/etiquettes': typeof AuthedEtiquettesRoute
  '/import': typeof AuthedImportRoute
  '/impression': typeof AuthedImpressionRoute
  '/recherche': typeof AuthedRechercheRoute
  '/sauvegarde': typeof AuthedSauvegardeRoute
  '/stock': typeof AuthedStockRoute
  '/vin': typeof AuthedVinRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authed/corbeille': typeof AuthedCorbeilleRoute
  '/_authed/entree': typeof AuthedEntreeRoute
  '/_authed/etiquettes': typeof AuthedEtiquettesRoute
  '/_authed/import': typeof AuthedImportRoute
  '/_authed/impression': typeof AuthedImpressionRoute
  '/_authed/recherche': typeof AuthedRechercheRoute
  '/_authed/sauvegarde': typeof AuthedSauvegardeRoute
  '/_authed/stock': typeof AuthedStockRoute
  '/_authed/vin': typeof AuthedVinRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/corbeille'
    | '/entree'
    | '/etiquettes'
    | '/import'
    | '/impression'
    | '/recherche'
    | '/sauvegarde'
    | '/stock'
    | '/vin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/corbeille'
    | '/entree'
    | '/etiquettes'
    | '/import'
    | '/impression'
    | '/recherche'
    | '/sauvegarde'
    | '/stock'
    | '/vin'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/auth'
    | '/_authed/corbeille'
    | '/_authed/entree'
    | '/_authed/etiquettes'
    | '/_authed/import'
    | '/_authed/impression'
    | '/_authed/recherche'
    | '/_authed/sauvegarde'
    | '/_authed/stock'
    | '/_authed/vin'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vin': {
      id: '/_authed/vin'
      path: '/vin'
      fullPath: '/vin'
      preLoaderRoute: typeof AuthedVinRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock': {
      id: '/_authed/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthedStockRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sauvegarde': {
      id: '/_authed/sauvegarde'
      path: '/sauvegarde'
      fullPath: '/sauvegarde'
      preLoaderRoute: typeof AuthedSauvegardeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recherche': {
      id: '/_authed/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof AuthedRechercheRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/impression': {
      id: '/_authed/impression'
      path: '/impression'
      fullPath: '/impression'
      preLoaderRoute: typeof AuthedImpressionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/import': {
      id: '/_authed/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthedImportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/etiquettes': {
      id: '/_authed/etiquettes'
      path: '/etiquettes'
      fullPath: '/etiquettes'
      preLoaderRoute: typeof AuthedEtiquettesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/entree': {
      id: '/_authed/entree'
      path: '/entree'
      fullPath: '/entree'
      preLoaderRoute: typeof AuthedEntreeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/corbeille': {
      id: '/_authed/corbeille'
      path: '/corbeille'
      fullPath: '/corbeille'
      preLoaderRoute: typeof AuthedCorbeilleRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCorbeilleRoute: typeof AuthedCorbeilleRoute
  AuthedEntreeRoute: typeof AuthedEntreeRoute
  AuthedEtiquettesRoute: typeof AuthedEtiquettesRoute
  AuthedImportRoute: typeof AuthedImportRoute
  AuthedImpressionRoute: typeof AuthedImpressionRoute
  AuthedRechercheRoute: typeof AuthedRechercheRoute
  AuthedSauvegardeRoute: typeof AuthedSauvegardeRoute
  AuthedStockRoute: typeof AuthedStockRoute
  AuthedVinRoute: typeof AuthedVinRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCorbeilleRoute: AuthedCorbeilleRoute,
  AuthedEntreeRoute: AuthedEntreeRoute,
  AuthedEtiquettesRoute: AuthedEtiquettesRoute,
  AuthedImportRoute: AuthedImportRoute,
  AuthedImpressionRoute: AuthedImpressionRoute,
  AuthedRechercheRoute: AuthedRechercheRoute,
  AuthedSauvegardeRoute: AuthedSauvegardeRoute,
  AuthedStockRoute: AuthedStockRoute,
  AuthedVinRoute: AuthedVinRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
